name: Cooking Toolchain
on: push

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: |
        sudo apt-get update
        sudo apt install bison ca-certificates ccache clang cmake curl file flex gcc g++ git make ninja-build python3 texinfo zlib1g-dev libssl-dev libelf-dev patchelf
        git checkout
        bash ./build.toolchain.sh
